name: PyLint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.11
    - name: Install dependencies
      run:
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run:
        find . -name '*.py' -not -path "*env/*" -exec pylint {} \;
    - name: Unit Testing
      run:
        pytest